### ISSUE TITLE
Relationship to mil_common

### ISSUE THREAD

**Issue by whispercoros** [uf-mil/odometry_tools#4]
This repository is dependent on messages from mil_common, but should be compilable on it's own. There are two prevailing opinions in the lab as to how we should proceed:

1. Move the messages to odometry_tools. They will still be included in mil_common since odometry_tools is one of it's submodules.

2. Absorb odometry_tools into mil_common. Since this is a package that is common to both active robots and is not a separate package we are planning on integrating, this could work. All history would be maintained in the process.

Does anyone have a strong opinion either way (especially @forrestv since this is mostly his work)?

**Comment by sentree** [comment]
This was addressed in uf-mil/mil_common#37.
